/* tslint:disable */
/* eslint-disable */
/**
 * BFF API
 * technical-verification backend for frontend Api Documentation.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: technical-verification@pm.nttdata-ccs.co.jp
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import globalAxios, {
  AxiosPromise,
  AxiosInstance,
  AxiosRequestConfig,
} from "axios";
// Some imports not used depending on template conditions
// @ts-ignore

/**
 * エラー情報
 * @export
 * @interface ApiError
 */
export interface ApiError {
  /**
   * エラーコード
   * @type {string}
   * @memberof ApiError
   */
  code?: string;
  /**
   * エラーメッセージ
   * @type {string}
   * @memberof ApiError
   */
  message?: string;
}
